# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Update Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * MON"

jobs:
  build:
    environment: PROD
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Run
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          EXCLUDE_REPOS: ${{ secrets.EXCLUDE_REPOS }}
          EXCLUDE_LANGS: ${{ secrets.EXCLUDE_LANGS }}
        run: go run -v ./cmd/language_stat_generator

      - name: Update Readme.md
        run: |
          git add Readme.md
          git add lang-stat.png
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update Readme.md"
          git push -u origin main
